schema_version: 1

context:
  python_min: "3.10"
  version: "1.5.0"

package:
  name: oda-reader
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/oda-reader/oda_reader-${{ version }}.tar.gz
  sha256: a4de2eda9a425ee6b4285a950bb8c644cdbc4d13e7758ec9e5502f96163feeaf

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.9.15,<0.10
    - pip
  run:
    - python >=${{ python_min }}
    - filelock >=3.20.3
    - joblib >=1.4
    - openpyxl >=3.1.0
    - pandas >=2.2.0
    - platformdirs >=4.5.0
    - pyarrow >=14.0.0
    - requests >=2.33.0
    - requests-cache >=1.2.0

tests:
  - python:
      imports:
        - oda_reader
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: "A simple package to import ODA data from the OECD's API and AidData's database"
  license: MIT
  license_file: LICENSE.txt
  homepage: https://pypi.org/project/oda-reader/

extra:
  recipe-maintainers:
    - brynpickering
    - jm-rivera
