schema_version: 1

context:
  python_min: "3.11"
  version: "1.9.0"

package:
  name: oda-reader
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/oda-reader/oda_reader-${{ version }}.tar.gz
  sha256: 5687c104ed6c0965e0349aec678a9d649244356844bbede12c39245e471592e6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.9.15,<0.10
    - pip
  run:
    - python >=${{ python_min }}
    - filelock >=3.20.3
    - inflate64 >=1.0.0
    - joblib >=1.4
    - openpyxl >=3.1.0
    - pandas >=2.2.0
    - platformdirs >=4.5.0
    - pyarrow >=23.0.1
    - requests >=2.33.0
    - requests-cache >=1.2.0

tests:
  - python:
      imports:
        - oda_reader
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: "A simple package to import ODA data from the OECD's API and AidData's database"
  license: MIT
  license_file: LICENSE.txt
  homepage: https://pypi.org/project/oda-reader/

extra:
  recipe-maintainers:
    - brynpickering
    - jm-rivera
